version: '3.8'

services:

  auth-db:
    build:
      context: ./dev-databases/auth
      dockerfile: Dockerfile
    container_name: auth-db
    ports:
      - "3400:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=auth_db
    volumes:
      - auth-data:/var/lib/mysql
    networks:
      - soa-network

  users-db:
    build:
      context: ./dev-databases/user
      dockerfile: Dockerfile
    container_name: users-db
    ports:
      - "3401:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=users_db
    volumes:
      - users-data:/var/lib/mysql
    networks:
      - soa-network

  materiales-db:
    build:
      context: ./dev-databases/materiales
      dockerfile: Dockerfile
    container_name: materiales-db
    ports:
      - "3402:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=materiales_db
    volumes:
      - materiales-data:/var/lib/mysql
    networks:
      - soa-network

  orden-db:
    build:
      context: ./dev-databases/orden
      dockerfile: Dockerfile
    container_name: orden-db
    ports:
      - "3403:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=orden_db
    volumes:
      - orden-data:/var/lib/mysql 
    networks:
      - soa-network

volumes:
  auth-data:
  users-data:
  materiales-data:
  orden-data:
networks:
  soa-network:
    driver: bridge 