CREATE TABLE auth (
    auth_id INT AUTO_INCREMENT PRIMARY KEY,
    auth_email CHAR VARYING(200) NOT NULL UNIQUE,
    auth_password CHAR VARYING(128) NOT NULL,
    auth_created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    auth_updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);
