version: '3.8'

services:
  auth-db:
    image: mysql:latest
    container_name: auth_schema
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: auth_db
    ports:
      - "3400:3306"
    volumes:
      - ./auth_schema.sql:/docker-entrypoint-initdb.d/init.sql
