version: '3.8'

services:
  user-db:
    image: mysql:latest
    container_name: user_db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: user_db
    ports:
      - "3400:3306"
    volumes:
      - ./user_schema.sql:/docker-entrypoint-initdb.d/init.sql